# NUMPY

#### Numpy is a Fundamental Package for scientific camputing in python. It is a Python Llibrary that provides a Multi Dimenstional Arry object and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discrete Fourier Transform, Basic Linear Algebra, Statical Operations, Random Simulation etc.

####  At the core of the Numpy Package is the n dimentional Array object.

### Why Numpy ? 
#### 2000 - 2009, Data science --> Matlab, R Language
#### Data types in Python --> List, Dictionary --> Slow Syntax --> Python --> Easy
#### We needed Speed and less Memory to work with the hug ammount of data.
#### Numpy --> c language --> wrapped --> Python language 
#### Numpy --> syntax --> Easy for beginners --> performing scientfic calculations --> Creating Multi Dimentional Arrays --> Speed is Faster for applying Operations --> Less memory
#### Libraries like Scikit learn, Tensorflow and pytorch require input data in Numpy Arrays or Tensors.

### Numpy Arrays Vs Python Sequences
#### Numpy Arrays have a fixed size at creation, unlike Python Lists which grew dynamically, Channing the size of an n dimetional array will create a new arry and delete the original.
#### The elements in a Numpy Array are required to be of the same data type and thus will be of the same size in memory .
#### Numpy Arrays facilitats advanced Mathemetical and other types of operations on large numer of data. Typically, such operations are executed more effeiciently with less code than is possible using Python's built in sequances.

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


### 1. np.arry() --> Creating the MultiDimenstional Arrays

In [2]:
import numpy as np

In [3]:
numpy_array = np.array([1,2,3,4,5,6,7])

In [4]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
type(numpy_array)

numpy.ndarray

In [8]:
TwoDArray = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [9]:
TwoDArray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [14]:
TwoDArray = np.array([[1,2,3,4,5],[6,7,8,9,0],[4,3,2,6,1]])

In [15]:
TwoDArray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [4, 3, 2, 6, 1]])

In [16]:
ThreeDArry = np.array([[[1,2],[2,3]],[[3,4],[4,5]],[[5,6],[6,7]]])

In [17]:
ThreeDArry

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]],

       [[5, 6],
        [6, 7]]])

In [18]:
FourDArray = np.array([[[[1,2],[2,3]],[[3,4],[4,5]]],[[[1,2],[2,3]],[[3,4],[4,5]]]])

In [19]:
FourDArray

array([[[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]]])

#### dtype parameter ---> Which can help us out with deciding about the size of the data we are going to store inside our array

In [2]:
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [3]:
np.array([7,6,8,9,10],dtype=np.int64)

array([ 7,  6,  8,  9, 10])

In [4]:
## np.float64, np.float32

In [5]:
np.array([11,12,13,22,32],dtype=float)

array([11., 12., 13., 22., 32.])

In [6]:
np.array([11,12,13,22,32],dtype=int)

array([11, 12, 13, 22, 32])

In [7]:
np.array([11,12,13,22,32],dtype=bool)

array([ True,  True,  True,  True,  True])

In [8]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


#### arange() --> It helps us out with providing the values over a certain range

In [9]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
arrange_data=np.arange(1,17)

#### np.reshape() --> It helps us out with changing the shape of the array as per our needs

In [17]:
arrange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
arrange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [21]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

#### ones()

In [22]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### zeros()


In [24]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### random() --> It helps us out with generating any random values from 0 to 1 inside our matrix 

In [28]:
np.random.random((3,4))

array([[0.66118772, 0.66601833, 0.30178946, 0.44555459],
       [0.3470104 , 0.77805386, 0.82732963, 0.77489644],
       [0.9450041 , 0.45332764, 0.88228083, 0.54853208]])

#### Identity() --> It helps us out with creating the matrix as an Identity Matrix (Squre Matrix --> Rows and Colums are must be equal)

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### linspace() --> it makes sure that every value with the given range is going to have similar distance from each other

In [31]:
np.linspace(20,40,10)

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

### Attributes

#### ndim --> mdim stands for n dimenstion

In [32]:
arr=np.array([1,2,3])

In [33]:
arr

array([1, 2, 3])

In [34]:
arr.ndim

1

In [41]:
np.identity(4).ndim

2

#### shape --> it provides us with the idea about the rows, colums in our dataset or in array

In [42]:
Array = np.array([[1,2,3],[4,5,6],[7,8,98]])

In [43]:
Array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 98]])

In [45]:
Array.shape

(3, 3)

In [51]:
ThreeDArry = np.array([[[1,2],[2,3]],[[1,2],[6,7]]])

In [52]:
ThreeDArry.shape

(2, 2, 2)

#### size() --> Total Number of Elements present inside our Dataset or array

In [53]:
array_elements=np.arange(5,54)

In [54]:
array_elements.size

49

#### itemsize --> provides with the idea about the size of a unique element inside our array in bytes

In [55]:
np.array([[[1,2],[2,3]],[[1,2],[6,7]]]).itemsize

8

#### dtype --> it provides us with the idea about the type of every item inside our array

In [56]:
np.array([[[1,2],[2,3]],[[1,2],[6,7]]], dtype=np.int32).itemsize

4

In [57]:
np.array([[[1,2],[2,3]],[[1,2],[6,7]]], dtype=np.int32)

array([[[1, 2],
        [2, 3]],

       [[1, 2],
        [6, 7]]], dtype=int32)

In [65]:
np.array([[[1,2],[2,3]],[[1,2],[6,7]]]).dtype

dtype('int64')

#### astype() --> astype() will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numpy as well for getting the data type changed of our overall array

In [72]:
array = np.array([[1,2,3],[4,5,6],[7,8,98]])

In [74]:
array = array.astype('float64')

In [75]:
array.dtype

dtype('float64')

## 2. Mathematical Operations in Numpy

#### Scalar Operations --> A scalar value operation will be done with the array or a numeric value 

In [77]:
array = np.random.random((3,3))*100

In [80]:
array=np.round(array)

In [81]:
array.astype('int32')

array([[29, 42, 77],
       [ 6, 17,  8],
       [54, 82, 86]], dtype=int32)

In [82]:
array

array([[29., 42., 77.],
       [ 6., 17.,  8.],
       [54., 82., 86.]])

In [83]:
## Scalar Operations with our Matrix or Array

In [84]:
array+2

array([[31., 44., 79.],
       [ 8., 19., 10.],
       [56., 84., 88.]])

In [85]:
a=5
b=6
print(a+b)

11


In [86]:
array-5

array([[24., 37., 72.],
       [ 1., 12.,  3.],
       [49., 77., 81.]])

In [87]:
array

array([[29., 42., 77.],
       [ 6., 17.,  8.],
       [54., 82., 86.]])

In [88]:
array*2

array([[ 58.,  84., 154.],
       [ 12.,  34.,  16.],
       [108., 164., 172.]])

In [89]:
array/2

array([[14.5, 21. , 38.5],
       [ 3. ,  8.5,  4. ],
       [27. , 41. , 43. ]])

In [90]:
## We can apply scalar operations with the array in term of arithmetic operations

In [91]:
a=5
b=6
a>b

False

In [92]:
array

array([[29., 42., 77.],
       [ 6., 17.,  8.],
       [54., 82., 86.]])

In [93]:
array>60

array([[False, False,  True],
       [False, False, False],
       [False,  True,  True]])

In [94]:
## Vector Operation --> Operations will be in between the given number of matrices

In [3]:
arr_1=np.arange(1,17).reshape(4,4)

In [4]:
arr_2=np.arange(17,33).reshape(4,4)

In [5]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
arr_1 + arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [9]:
arr_2 - arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [10]:
arr_1 * arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

## Important Functions in Numpy for Machine Learning and Data Science

### 1. max() --> It is going to be used to calculate the max value inside a matrix or an array 
#### syntax for max() --> np.max(array)

In [14]:
max_array = np.arange(1,33,2).reshape(4,4)

In [15]:
max_array

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [21]:
array1 = np.random.random((3,3))*100

In [24]:
array1 = array1.astype('int32')

In [25]:
array1

array([[42, 39, 21],
       [66, 39, 76],
       [11, 79, 40]], dtype=int32)

In [26]:
np.max(max_array)

np.int64(31)

In [28]:
max_value = np.max(max_array)

In [29]:
max_value

np.int64(31)

In [27]:
np.max(array1)

np.int32(79)

In [30]:
array_data = np.round(np.random.random((4,4))*100).astype('int32')

In [31]:
array_data

array([[50, 70, 81, 73],
       [70, 71, 32, 83],
       [96, 82, 24, 62],
       [38, 75,  3, 14]], dtype=int32)

### 2. axis --> It provides us with the idea about the any operation value inside a specific row or column or we can get a specific value row wise or column wise

#### axis = 0  --> column wise operation 
#### axis = 1 --> row wise operation

In [32]:
axis_array = np.round(np.random.random((4,4))*100).astype('int32')

In [34]:
axis_array

array([[36, 13, 75,  8],
       [70, 59, 89,  1],
       [21, 83, 83, 40],
       [30, 19, 90, 37]], dtype=int32)

In [33]:
np.max(axis_array,axis=0)

array([70, 83, 90, 40], dtype=int32)

In [35]:
np.max(axis_array,axis=1)

array([75, 89, 83, 90], dtype=int32)

### 3. min() --> it will be used for calculating the minimum value from the matrix or array
#### syntax --> np.min()

In [36]:
min_array = np.round(np.random.random((5,5))*100).astype('int32')

In [37]:
min_array

array([[ 1,  2, 96, 69, 18],
       [81, 54, 56, 50, 66],
       [80, 33, 34, 18, 89],
       [ 6, 12, 71, 94, 92],
       [37, 14, 60, 57,  0]], dtype=int32)

In [38]:
np.min(min_array)

np.int32(0)

In [39]:
np.min(min_array,axis=0)

array([ 1,  2, 34, 18,  0], dtype=int32)

In [40]:
np.min(min_array,axis=1)

array([ 1, 50, 18,  6,  0], dtype=int32)

### 3. sum() --> calculates the sum of all of the values of a given matrix
#### syntax for sum() --> np.sum()

In [41]:
sum_array = np.round(np.random.random((5,5))*100).astype('int32')

In [42]:
sum_array

array([[56,  1, 26, 65, 33],
       [62, 42, 72, 46,  5],
       [19, 63, 90, 37, 77],
       [32, 13, 25, 69, 34],
       [42, 92, 62, 86, 95]], dtype=int32)

In [43]:
np.sum(sum_array)

np.int64(1244)

In [44]:
np.sum(sum_array,axis=0)

array([211, 211, 275, 303, 244])

In [45]:
np.sum(sum_array,axis=1)

array([181, 227, 286, 173, 377])

### 4. prod() --> it helps with calculating the product of all values inside the matrix
#### syntax --> np.prod()

In [46]:
product_array = np.round(np.random.random((5,5))*100).astype('int32')

In [47]:
product_array

array([[38, 19, 19, 45, 30],
       [20, 95, 66, 28, 25],
       [53, 35, 11, 11, 50],
       [ 4, 21, 68, 85, 53],
       [16, 96, 39, 37, 13]], dtype=int32)

In [48]:
np.prod(product_array)

np.int64(2595218470209585152)

In [49]:
np.prod(product_array,axis=0)

array([  2577920, 127360800,  36581688,  43589700,  25837500])

In [50]:
np.prod(product_array,axis=1)

array([18519300, 87780000, 11222750, 25732560, 28813824])

## Statistical functions in Mumpy

### 1. mean() --> syntax for mean() --> np.mean() --> mean of all values inside the array or matrix

In [51]:
mean_array = np.round(np.random.random((5,5))*100).astype('int32')

In [52]:
mean_array

array([[75, 25, 43, 18, 71],
       [69,  5, 10, 86,  2],
       [12, 59, 11, 75, 26],
       [ 5, 54, 87, 93,  7],
       [69, 73, 14, 17, 78]], dtype=int32)

In [53]:
np.mean(mean_array)

np.float64(43.36)

In [54]:
np.mean(mean_array,axis=0)

array([46. , 43.2, 33. , 57.8, 36.8])

In [55]:
np.mean(mean_array,axis=1)

array([46.4, 34.4, 36.6, 49.2, 50.2])

### 2. std() --> it provides with the standard deviation of all values of the matrix or array

In [56]:
std_array = np.round(np.random.random((5,5))*100).astype('int32')

In [57]:
std_array

array([[ 9, 80, 51,  2, 85],
       [87, 15, 59,  7, 59],
       [37, 35, 98, 73, 88],
       [36, 93, 25, 14, 80],
       [55,  2, 31, 91, 22]], dtype=int32)

In [58]:
np.std(std_array)

np.float64(31.873349369026155)

In [59]:
np.std(std_array,axis=0)

array([25.70914234, 35.71554284, 25.8178233 , 37.05455438, 24.58780185])

In [60]:
np.std(std_array,axis=1)

array([34.65602401, 29.99733321, 25.91833328, 31.19358908, 30.57711563])

### 3. median() --> To calculates median of all values in the array or matrix
#### syntax for median --> np.median()

In [61]:
median_array = np.round(np.random.random((5,5))*100).astype('int32')

In [62]:
median_array

array([[15, 29, 34, 43, 13],
       [57, 98, 54, 81, 48],
       [92, 18, 82, 15, 93],
       [80, 34, 26, 29, 78],
       [62, 72, 10, 55, 55]], dtype=int32)

In [63]:
np.median(median_array)

np.float64(54.0)

In [64]:
np.median(median_array,axis=0)

array([62., 34., 34., 43., 55.])

In [65]:
np.median(median_array,axis=1)

array([29., 57., 82., 34., 55.])

### var --> It helps with calculating the variance of all values inside the array or matrix
#### syntax --> np.var()

In [66]:
var_array = np.round(np.random.random((5,5))*100).astype('int32')

In [67]:
var_array

array([[20, 47, 14, 77, 35],
       [37, 25, 60,  6, 76],
       [73, 27, 37, 11, 18],
       [ 3, 69, 13, 40, 18],
       [81, 82, 28, 16, 39]], dtype=int32)

In [68]:
np.var(var_array)

np.float64(627.7535999999999)

In [69]:
np.var(var_array,axis=0)

array([901.76, 509.6 , 299.44, 688.4 , 450.16])

In [70]:
np.var(var_array,axis=1)

array([501.84, 616.56, 472.16, 554.64, 748.56])

## Trigonometric Functions

### 1. sin() --> sin value for the value we are going to pass inside it

In [80]:
np.sin(0)

np.float64(0.0)

In [81]:
np.sin(45)

np.float64(0.8509035245341184)

In [82]:
np.sin(60)

np.float64(-0.3048106211022167)

In [83]:
np.tan(45)

np.float64(1.6197751905438615)

## 1. DOT Product of Matrices
#### syntax for Dot Product --> np.dot(matrix1,matrix2)

In [90]:
matrix_1 = np.round(np.random.random((3,3))*100).astype('int32')
matrix_2 = np.round(np.random.random((3,3))*100).astype('int32')

In [91]:
matrix_1

array([[33, 62, 70],
       [61, 81, 23],
       [25, 85, 58]], dtype=int32)

In [92]:
matrix_2

array([[57, 52, 82],
       [11, 45, 79],
       [ 9, 16,  1]], dtype=int32)

In [93]:
np.dot(matrix_1,matrix_2)

array([[ 3193,  5626,  7674],
       [ 4575,  7185, 11424],
       [ 2882,  6053,  8823]], dtype=int32)

## 2. log() --> To calculate the log of all values of our matrix
#### syntax for log() --> np.log()

In [3]:
log_array = np.round(np.random.random((3,4))*100).astype('int32')

In [4]:
log_array

array([[35, 85, 19,  2],
       [ 2, 92, 15, 53],
       [ 2,  1, 79, 76]], dtype=int32)

In [5]:
np.log(log_array)

array([[3.55534806, 4.44265126, 2.94443898, 0.69314718],
       [0.69314718, 4.52178858, 2.7080502 , 3.97029191],
       [0.69314718, 0.        , 4.36944785, 4.33073334]])

## 3. exp() --> exponential of all values inside the Matrix
#### syntax --> np.exp()

In [6]:
exp_array = np.round(np.random.random((3,4))*100).astype('int32')

In [7]:
exp_array

array([[62, 96, 39, 51],
       [71, 97, 56, 75],
       [92, 64, 56, 49]], dtype=int32)

In [8]:
np.exp(exp_array)

array([[8.43835667e+26, 4.92345829e+41, 8.65934004e+16, 1.40934908e+22],
       [6.83767123e+30, 1.33833472e+42, 2.09165950e+24, 3.73324200e+32],
       [9.01762841e+39, 6.23514908e+27, 2.09165950e+24, 1.90734657e+21]])

## 4. round() --> it helps with rounding off the float values to its nearest possible integer value

#### syntax for round() --> np.round()
#### round of value for 1.7 --> 2
#### 1.3 --> 1

In [9]:
array = np.random.random((3,4))

In [10]:
array

array([[0.21876512, 0.91303792, 0.77938691, 0.70914336],
       [0.59742892, 0.41111713, 0.39601887, 0.329777  ],
       [0.03119053, 0.92232686, 0.07120071, 0.52407542]])

In [11]:
array*10

array([[2.18765125, 9.13037915, 7.79386913, 7.09143362],
       [5.97428915, 4.11117131, 3.9601887 , 3.29777   ],
       [0.31190527, 9.22326862, 0.71200714, 5.24075421]])

In [12]:
np.round(array)

array([[0., 1., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 1.]])

## 5. ceil() --> Next corresponding value
#### syntax --> np.ceil()

In [16]:
array = np.random.random((3,4))*100

In [17]:
array

array([[54.90643642, 78.94507156, 50.22102757, 73.40721891],
       [70.70832476,  4.33875987,  8.47839373,  3.40578197],
       [26.39198523, 32.73549081,  6.76616401, 41.46768801]])

In [18]:
np.ceil(array)

array([[55., 79., 51., 74.],
       [71.,  5.,  9.,  4.],
       [27., 33.,  7., 42.]])

## 6. floor() --> It can provide us with the previous value
#### syntax --> np.floor()

In [19]:
array = np.random.random((3,4))*100

In [21]:
array

array([[74.18430588, 38.79665165, 92.08376386, 53.6659042 ],
       [52.53063009, 44.47223999, 86.90247373, 71.66366676],
       [63.64419426, 75.55699457, 70.79279284, 18.69384201]])

In [20]:
np.floor(array)

array([[74., 38., 92., 53.],
       [52., 44., 86., 71.],
       [63., 75., 70., 18.]])

## 7. Transpose() --> It calculates the transpose of the given matrix
#### Transpose syntax --> np.transpose(arr) or arr.T
#### Transpose --> (i,j) --> (j,i) --> (3,4) --> T --> (4,3)

In [22]:
array = np.arange(1,17).reshape(4,4)

In [23]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [26]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
np.transpose(array)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

## 8. ravel() --> Convert nd array into 1d array
#### syntax --> np.ravel()

In [29]:
array = np.arange(1,32,2).reshape(4,4)

In [30]:
array

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [31]:
array.ndim

2

In [32]:
np.ravel(array)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

## Indexing and Slicing in Numpy

### Indexing --> To have the access over the values
#### lists[,size-1]

In [33]:
array = np.round(np.random.random((5,5))*100).astype('int32')

In [34]:
array

array([[70, 14, 52, 27, 65],
       [79, 25, 76, 29, 96],
       [76, 49, 37, 70, 24],
       [85, 98, 86, 21, 61],
       [80, 66, 14, 14, 54]], dtype=int32)

In [35]:
array_one = np.arange(1,10)

In [36]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
array_one[6]

np.int64(7)

In [38]:
array_one[8]

np.int64(9)

### Indexing in 2D Array --> [row,column]

In [41]:
array

array([[70, 14, 52, 27, 65],
       [79, 25, 76, 29, 96],
       [76, 49, 37, 70, 24],
       [85, 98, 86, 21, 61],
       [80, 66, 14, 14, 54]], dtype=int32)

In [42]:
array[4,4]

np.int32(54)

### Indexing in 3D Array --> [z-axis, x-axis, y-axis]

In [43]:
array_three = np.arange(1,9).reshape(2,2,2)

In [44]:
array_three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
array_three[1,0,1]

np.int64(6)

In [46]:
array_three[0,1,0]

np.int64(3)

In [47]:
array

array([[70, 14, 52, 27, 65],
       [79, 25, 76, 29, 96],
       [76, 49, 37, 70, 24],
       [85, 98, 86, 21, 61],
       [80, 66, 14, 14, 54]], dtype=int32)

### Slicing --> Slicing approch just like the list [:]
#### 2D array --> [row_1:row_2,col_1:col_2]

In [54]:
array = np.round(np.random.random((5,5))*100).astype('int32')

In [55]:
array

array([[ 90,  92,  66,  51,  31],
       [ 67,   0,  62,  32,  52],
       [ 88,  37,  31,  88,  89],
       [ 61,  61,  61,  37, 100],
       [ 35,  81,  23,  45,  48]], dtype=int32)

In [56]:
array[:,2]

array([66, 62, 31, 61, 23], dtype=int32)

In [57]:
array[0,:]

array([90, 92, 66, 51, 31], dtype=int32)

In [58]:
array

array([[ 90,  92,  66,  51,  31],
       [ 67,   0,  62,  32,  52],
       [ 88,  37,  31,  88,  89],
       [ 61,  61,  61,  37, 100],
       [ 35,  81,  23,  45,  48]], dtype=int32)

In [60]:
array[2:4,3:5]

array([[ 88,  89],
       [ 37, 100]], dtype=int32)

In [61]:
array[2:,1:4]

array([[37, 31, 88],
       [61, 61, 37],
       [81, 23, 45]], dtype=int32)

#### Iterating over an Array

In [62]:
array = np.arange(1,10)

In [63]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [64]:
array = np.arange(1,17).reshape(4,4)

In [65]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [69]:
array = np.arange(1,28).reshape(3,3,3)

In [70]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [71]:
for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


### nditer() --> It can help us not with iterating over every value in a nd array
#### np.nditer()

In [72]:
array = np.arange(1,28).reshape(3,3,3)

In [73]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [74]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [75]:
# 1D Array --> value by value on iteration
# 2D Array --> Row by Row on iteration
# 3D Array --> 2d Array by 2D Array

## Stacking and Spliting

#### Stacking --> Joining The Arrays Together
#### Horizontal Stacking --> Now by Row joining is done --> hstack()
#### Vertical Stacking --> Column by Column Joining is done --> vstack()
#### Horizontal split --> np.hsplit(array,number of parts you want your array to be splitted at)
#### vertical split --> np.vsplit(array,number of parts)

In [2]:
import numpy as np

In [3]:
array_one = np.arange(1,13).reshape(3,4)

In [4]:
array_one

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
array_two = np.arange(13,25).reshape(3,4)

In [6]:
array_two

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

#### Horizontal Stacking --> Now by Row joining is done --> hstack()

In [7]:
horizontal_array = np.hstack((array_one,array_two))

In [8]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [9]:
horizontal_array = np.hstack((array_one,array_two,array_one,array_two))

In [10]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16,  1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20,  5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24,  9, 10, 11, 12, 21, 22, 23, 24]])

#### Vertical Stacking --> Column by Column Joining is done --> vstack()

In [11]:
vertical_array = np.vstack((array_one,array_two))

In [12]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

#### Horizontal split --> np.hsplit(array,number of parts you want your array to be splitted at)

In [14]:
np.hsplit(vertical_array,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

#### vertical split --> np.vsplit(array,number of parts)

In [15]:
np.vsplit(vertical_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [16]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [17]:
np.vsplit(vertical_array,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]